name: Run Python Script

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to process'
        required: true
      recipients:
        description: 'Recipients of the message'
        required: true
      email:
        description: 'Email for authentication'
        required: true
      password:
        description: 'Password for authentication'
        required: true

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Python script
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Securely pass the GitHub token
      run: |
        python MOE_Reports.py "${{ github.event.inputs.url }}" "${{ github.event.inputs.recipients }}" "${{ github.event.inputs.email }}" "${{ github.event.inputs.password }}" "${{ env.TOKEN }}"
